# Generated by Django 3.0 on 2021-06-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0002_auto_20210628_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ue',
            name='academic_year',
            field=models.CharField(choices=[('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], default='2020/2021', max_length=9),
        ),
        migrations.AlterField(
            model_name='ue_questions_results',
            name='academic_year',
            field=models.CharField(choices=[('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], default='2020/2021', max_length=9),
        ),
        migrations.AlterField(
            model_name='ue_results',
            name='academic_year',
            field=models.CharField(choices=[('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], default='2020/2021', max_length=9),
        ),
    ]
