# Generated by Django 3.0 on 2021-05-09 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0002_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='average',
        ),
        migrations.AlterField(
            model_name='result',
            name='first_question',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='result',
            name='fourth_question',
            field=models.IntegerField(default=8, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='result',
            name='second_question',
            field=models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='result',
            name='third_question',
            field=models.IntegerField(default=7, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
