# Generated by Django 3.0 on 2021-05-19 13:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0004_auto_20210511_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_Criteria',
            fields=[
                ('criteria_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('program_span', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('regno', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('program', models.ForeignKey(on_delete=models.SET('empty'), related_name='program', to='backendapi.Program')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=30)),
                ('academic_year', models.CharField(max_length=5)),
                ('date_taken', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('total_mark', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Total marks')),
                ('number_of_questions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue', to='backendapi.Course')),
            ],
            options={
                'unique_together': {('course', 'exam_type', 'academic_year', 'date_taken', 'total_mark', 'number_of_questions')},
            },
        ),
        migrations.AlterModelOptions(
            name='lecturer',
            options={'verbose_name': 'lecturer', 'verbose_name_plural': 'lecturers'},
        ),
        migrations.CreateModel(
            name='Program_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.Course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.Program')),
            ],
            options={
                'unique_together': {('course', 'program', 'year_of_study')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ManyToManyField(through='backendapi.Program_Course', to='backendapi.Program'),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=5)),
                ('date_taken', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('total_mark', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Total marks')),
                ('number_of_questions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('contribution', models.IntegerField(validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)], verbose_name='Contribution in Percentage')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='backendapi.Course')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='backendapi.Assessment_Criteria')),
            ],
            options={
                'unique_together': {('course', 'contribution', 'criteria', 'academic_year', 'date_taken', 'total_mark', 'number_of_questions')},
            },
        ),
        migrations.CreateModel(
            name='UE_Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('total_score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('question_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='backendapi.Student')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='backendapi.UE')),
            ],
            options={
                'unique_together': {('score', 'total_score', 'question_number', 'student', 'ue')},
            },
        ),
        migrations.CreateModel(
            name='Lecture_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to='backendapi.Course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='backendapi.Lecturer')),
            ],
            options={
                'unique_together': {('lecturer', 'course', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Assessment_Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('total_score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('question_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='backendapi.Assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_result', to='backendapi.Student')),
            ],
            options={
                'unique_together': {('score', 'total_score', 'question_number', 'student', 'assessment')},
            },
        ),
    ]
