# Generated by Django 3.0 on 2021-05-20 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0005_auto_20210519_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='course',
            field=models.ManyToManyField(through='backendapi.Lecture_Course', to='backendapi.Course'),
        ),
        migrations.AlterField(
            model_name='lecture_course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.Course'),
        ),
        migrations.AlterField(
            model_name='lecture_course',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.Lecturer'),
        ),
    ]
