# Generated by Django 3.0 on 2021-05-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0006_auto_20210520_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_course',
            name='academic_year',
            field=models.CharField(choices=[('a', '2020/2021'), ('b', '2021/2022'), ('c', '2022/2023'), ('d', '2023/2024')], default='a', max_length=9),
        ),
    ]
