# Generated by Django 3.0 on 2021-05-20 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0007_auto_20210520_0218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecture_course',
            unique_together=set(),
        ),
    ]
