# Generated by Django 3.0 on 2021-05-20 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0008_auto_20210520_0220'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecture_course',
            unique_together={('lecturer', 'course', 'academic_year')},
        ),
    ]
