# Generated by Django 3.0 on 2021-05-20 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0010_auto_20210520_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='time',
            field=models.CharField(choices=[('a', '7:00 am'), ('b', '8:00 am'), ('c', '9:00 am'), ('d', '10:00 am'), ('e', '11:00 am'), ('f', '12:00 pm'), ('g', '13:00 pm'), ('h', '14:00 pm'), ('i', '15:00 pm'), ('j', '16:00 pm'), ('k', '17:00 pm'), ('l', '18:00 pm')], default='a', max_length=8),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='academic_year',
            field=models.CharField(choices=[('a', '2020/2021'), ('b', '2021/2022'), ('c', '2022/2023'), ('d', '2023/2024')], default='a', max_length=9),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date_taken',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='number_of_questions',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
