# Generated by Django 3.0 on 2021-05-20 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0012_auto_20210520_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='contribution',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)], verbose_name='Contribution in Percentage'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='total_mark',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Total marks'),
        ),
    ]
