# Generated by Django 3.0 on 2021-05-20 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0013_auto_20210520_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='contribution',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)], verbose_name='Contribution to CA in Percentage'),
        ),
    ]
