# Generated by Django 3.0 on 2021-05-20 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0014_auto_20210520_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_results',
            name='question_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='assessment_results',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='assessment_results',
            name='total_score',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
