# Generated by Django 3.0 on 2021-05-20 03:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0015_auto_20210520_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_results',
            name='question_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
    ]
