# Generated by Django 3.0 on 2021-05-21 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backendapi', '0018_auto_20210520_0408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecturer',
            unique_together={('lecturer', 'role')},
        ),
    ]
