# Generated by Django 3.0 on 2021-05-23 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0019_auto_20210521_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture_course',
            name='assessmentCriteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapi.Assessment_Criteria'),
        ),
        migrations.AlterUniqueTogether(
            name='lecture_course',
            unique_together={('lecturer', 'course', 'assessmentCriteria', 'academic_year')},
        ),
    ]
