# Generated by Django 3.0 on 2021-05-24 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0022_remove_lecture_course_assessmentcriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessmentCriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='backendapi.Assessment_Criteria')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_criteria', to='backendapi.Lecturer')),
            ],
            options={
                'unique_together': {('lecturer', 'assessmentCriteria')},
            },
        ),
        migrations.AddField(
            model_name='lecturer',
            name='criteria',
            field=models.ManyToManyField(through='backendapi.LecturerCriteria', to='backendapi.Assessment_Criteria'),
        ),
    ]
