# Generated by Django 3.0 on 2021-05-24 00:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0023_auto_20210524_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture_course',
            name='assessmentCriteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapi.Assessment_Criteria'),
        ),
        migrations.AddField(
            model_name='lecture_course',
            name='ca_contribution',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='lecturercriteria',
            name='ca_contribution',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(0)]),
        ),
    ]
