# Generated by Django 3.0 on 2021-05-26 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0024_auto_20210524_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_course',
            name='academic_year',
            field=models.CharField(choices=[('a', '2020/2021'), ('b', '2021/2022'), ('c', '2022/2023'), ('d', '2023/2024')], default='a', max_length=9),
        ),
        migrations.AddField(
            model_name='program_course',
            name='is_compulsory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program_course',
            name='semester',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='lecture_course',
            unique_together={('lecturer', 'course', 'academic_year', 'assessmentCriteria')},
        ),
        migrations.AlterUniqueTogether(
            name='program_course',
            unique_together={('course', 'program', 'year_of_study', 'semester', 'academic_year')},
        ),
    ]
