# Generated by Django 3.0 on 2021-05-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0025_auto_20210526_0149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assessment_Criteria',
            new_name='CA_Items',
        ),
        migrations.RenameField(
            model_name='ca_items',
            old_name='criteria_name',
            new_name='ca_item_name',
        ),
    ]
