# Generated by Django 3.0 on 2021-05-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0026_auto_20210526_0941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CA_Items',
            new_name='CA_Item',
        ),
    ]
