# Generated by Django 3.0 on 2021-05-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0028_auto_20210526_0950'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('course', 'contribution', 'criteria', 'academic_year', 'date_taken', 'number_of_questions')},
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='total_mark',
        ),
    ]
