# Generated by Django 3.0 on 2021-05-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0033_auto_20210526_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='academic_year',
            field=models.CharField(choices=[('a', '2020/2021'), ('b', '2021/2022'), ('c', '2022/2023'), ('d', '2023/2024'), ('e', '2024/2025'), ('f', '2025/2026')], default='a', max_length=9),
        ),
        migrations.AlterField(
            model_name='lecture_course',
            name='academic_year',
            field=models.CharField(choices=[('a', '2020/2021'), ('b', '2021/2022'), ('c', '2022/2023'), ('d', '2023/2024'), ('e', '2024/2025'), ('f', '2025/2026')], default='a', max_length=9),
        ),
        migrations.AlterField(
            model_name='program_course',
            name='academic_year',
            field=models.CharField(choices=[('a', '2020/2021'), ('b', '2021/2022'), ('c', '2022/2023'), ('d', '2023/2024'), ('e', '2024/2025'), ('f', '2025/2026')], default='a', max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='program_course',
            unique_together={('course', 'program', 'academic_year', 'semester', 'course_type', 'year_of_study')},
        ),
    ]
