# Generated by Django 3.0 on 2021-05-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0036_auto_20210527_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='sum',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('course', 'criteria')},
        ),
    ]
