# Generated by Django 3.0 on 2021-05-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0038_auto_20210527_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecture_course',
            unique_together={('lecturer', 'course', 'academic_year')},
        ),
        migrations.RemoveField(
            model_name='lecture_course',
            name='assessmentCriteria',
        ),
        migrations.RemoveField(
            model_name='lecture_course',
            name='ca_contribution',
        ),
    ]
