# Generated by Django 3.0 on 2021-05-28 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0039_auto_20210527_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='CA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.IntegerField()),
                ('academic_year', models.CharField(choices=[('a', '2020/2021'), ('b', '2021/2022'), ('c', '2022/2023'), ('d', '2023/2024'), ('e', '2024/2025'), ('f', '2025/2026')], default='a', max_length=9)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapi.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='criteria',
        ),
        migrations.DeleteModel(
            name='LecturerCriteria',
        ),
    ]
