# Generated by Django 3.0 on 2021-05-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0040_auto_20210528_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='ca',
            field=models.IntegerField(null=True),
        ),
    ]
