# Generated by Django 3.0 on 2021-05-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0043_remove_assessment_results_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='academic_year',
            field=models.CharField(choices=[('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], default='2020/2021', max_length=9),
        ),
    ]
