# Generated by Django 3.0 on 2021-05-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0044_auto_20210530_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(choices=[('12', 12), ('8', 8)], default='12'),
        ),
    ]
