# Generated by Django 3.0 on 2021-05-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0045_course_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=12),
        ),
    ]
