# Generated by Django 3.0 on 2021-06-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0047_auto_20210531_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date_taken',
            field=models.CharField(max_length=9, verbose_name='Date'),
        ),
    ]
