# Generated by Django 3.0 on 2021-06-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0048_auto_20210601_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date_taken',
            field=models.CharField(max_length=10, verbose_name='Date'),
        ),
    ]
