# Generated by Django 3.0 on 2021-06-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0049_auto_20210601_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date_taken',
            field=models.CharField(max_length=10, null=True, verbose_name='Date'),
        ),
    ]
