# Generated by Django 3.0 on 2021-06-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0050_auto_20210602_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='date_taken',
            field=models.CharField(max_length=10, verbose_name='Date'),
        ),
    ]
