# Generated by Django 3.0 on 2021-06-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0051_auto_20210602_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='academic_year',
            field=models.CharField(choices=[('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025'), ('2025/2026', '2025/2026')], default='2020/2021', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date_taken',
            field=models.CharField(max_length=10, null=True, verbose_name='Date'),
        ),
    ]
