# Generated by Django 3.0 on 2021-06-29 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0053_auto_20210628_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment_results',
            name='academic_year',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='assessment_results',
            name='course_type',
            field=models.CharField(default='core', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assessment_results',
            name='semester',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='assessment_results',
            name='year_of_study',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
