# Generated by Django 3.0 on 2021-05-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210508_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
