# Generated by Django 3.0 on 2021-05-08 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0015_auto_20210508_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='Lecturer', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='Lecturer', max_length=20)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Role')),
            ],
        ),
    ]
