# Generated by Django 3.0 on 2021-05-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_lecturer_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='role_name',
        ),
    ]
