# Generated by Django 3.0 on 2021-05-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210508_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
